<?php
 /**
 * 2007-2023 PrestaShop
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 *
 * @author    yourName
 * @copyright 2007-2023 
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 * @generated by PrestashopConsole  / copyright 2016-2023 Hennes Hervé http://www.h-hennes.fr/blog/
 */
 

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * Upgrade module 0_2_1 Add a configuration for log max file size
 * @param Module $module
 * @return bool
 */
function upgrade_module_0_2_1(Module $module):bool
{
    return Configuration::updateValue('HHCSPHEADERS_LOG_MAX_FILE_SIZE',10);
}
