name: PHP tests
on: [ push, pull_request ]
jobs:
  php-linter:
    name: PHP Syntax check 7.2|7.3|7.4|8.0|8.1|8.2
    runs-on: ubuntu-latest
    steps:
      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master
      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master

  # Check the PHP code follow the coding standards
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Run PHP-CS-Fixer
        uses: prestashopcorp/github-action-php-cs-fixer@master